version: "3.8"

services:
  app:
    image: posts-service:1.0
    command: ./homework-5

    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DBNAME=${DBNAME}

      - HTTP_HOST=${HTTP_HOST}
      - HTTP_PORT=${HTTP_PORT}


    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - default

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
